package cn.bandu.oreader.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import cn.bandu.oreader.dao.ArticleList;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ARTICLE_LIST.
*/
public class ArticleListDao extends AbstractDao<ArticleList, Long> {

    public static final String TABLENAME = "ARTICLE_LIST";

    /**
     * Properties of entity ArticleList.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Sid = new Property(0, long.class, "sid", true, "SID");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Description = new Property(2, String.class, "description", false, "DESCRIPTION");
        public final static Property Date = new Property(3, String.class, "date", false, "DATE");
        public final static Property WebUrl = new Property(4, String.class, "webUrl", false, "WEB_URL");
        public final static Property Image0 = new Property(5, String.class, "image0", false, "IMAGE0");
        public final static Property Image1 = new Property(6, String.class, "image1", false, "IMAGE1");
        public final static Property Image2 = new Property(7, String.class, "image2", false, "IMAGE2");
        public final static Property Model = new Property(8, Integer.class, "model", false, "MODEL");
    };


    public ArticleListDao(DaoConfig config) {
        super(config);
    }
    
    public ArticleListDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ARTICLE_LIST' (" + //
                "'SID' INTEGER PRIMARY KEY ASC NOT NULL ," + // 0: sid
                "'TITLE' TEXT NOT NULL ," + // 1: title
                "'DESCRIPTION' TEXT," + // 2: description
                "'DATE' TEXT," + // 3: date
                "'WEB_URL' TEXT NOT NULL ," + // 4: webUrl
                "'IMAGE0' TEXT," + // 5: image0
                "'IMAGE1' TEXT," + // 6: image1
                "'IMAGE2' TEXT," + // 7: image2
                "'MODEL' INTEGER);"); // 8: model
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ARTICLE_LIST'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ArticleList entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getSid());
        stmt.bindString(2, entity.getTitle());
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(3, description);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(4, date);
        }
        stmt.bindString(5, entity.getWebUrl());
 
        String image0 = entity.getImage0();
        if (image0 != null) {
            stmt.bindString(6, image0);
        }
 
        String image1 = entity.getImage1();
        if (image1 != null) {
            stmt.bindString(7, image1);
        }
 
        String image2 = entity.getImage2();
        if (image2 != null) {
            stmt.bindString(8, image2);
        }
 
        Integer model = entity.getModel();
        if (model != null) {
            stmt.bindLong(9, model);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ArticleList readEntity(Cursor cursor, int offset) {
        ArticleList entity = new ArticleList( //
            cursor.getLong(offset + 0), // sid
            cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // description
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // date
            cursor.getString(offset + 4), // webUrl
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // image0
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // image1
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // image2
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8) // model
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ArticleList entity, int offset) {
        entity.setSid(cursor.getLong(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setDescription(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDate(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setWebUrl(cursor.getString(offset + 4));
        entity.setImage0(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setImage1(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setImage2(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setModel(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ArticleList entity, long rowId) {
        entity.setSid(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ArticleList entity) {
        if(entity != null) {
            return entity.getSid();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
