package cn.bandu.oreader.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table CATE.
 */
public class Cate implements Serializable {

    private Long id;
    private long sid;
    /** Not-null value. */
    private String name;

    public Cate() {
    }

    public Cate(Long id) {
        this.id = id;
    }

    public Cate(Long id, long sid, String name) {
        this.id = id;
        this.sid = sid;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getSid() {
        return sid;
    }

    public void setSid(long sid) {
        this.sid = sid;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

}
