package cn.bandu.oreader.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import cn.bandu.oreader.dao.Fav;

import cn.bandu.oreader.dao.FavDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favDaoConfig;

    private final FavDao favDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favDaoConfig = daoConfigMap.get(FavDao.class).clone();
        favDaoConfig.initIdentityScope(type);

        favDao = new FavDao(favDaoConfig, this);

        registerDao(Fav.class, favDao);
    }
    
    public void clear() {
        favDaoConfig.getIdentityScope().clear();
    }

    public FavDao getFavDao() {
        return favDao;
    }

}
