package cn.bandu.oreader.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import cn.bandu.oreader.dao.Fav;
import cn.bandu.oreader.dao.Cate;
import cn.bandu.oreader.dao.ArticleList;

import cn.bandu.oreader.dao.FavDao;
import cn.bandu.oreader.dao.CateDao;
import cn.bandu.oreader.dao.ArticleListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favDaoConfig;
    private final DaoConfig cateDaoConfig;
    private final DaoConfig articleListDaoConfig;

    private final FavDao favDao;
    private final CateDao cateDao;
    private final ArticleListDao articleListDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favDaoConfig = daoConfigMap.get(FavDao.class).clone();
        favDaoConfig.initIdentityScope(type);

        cateDaoConfig = daoConfigMap.get(CateDao.class).clone();
        cateDaoConfig.initIdentityScope(type);

        articleListDaoConfig = daoConfigMap.get(ArticleListDao.class).clone();
        articleListDaoConfig.initIdentityScope(type);

        favDao = new FavDao(favDaoConfig, this);
        cateDao = new CateDao(cateDaoConfig, this);
        articleListDao = new ArticleListDao(articleListDaoConfig, this);

        registerDao(Fav.class, favDao);
        registerDao(Cate.class, cateDao);
        registerDao(ArticleList.class, articleListDao);
    }
    
    public void clear() {
        favDaoConfig.getIdentityScope().clear();
        cateDaoConfig.getIdentityScope().clear();
        articleListDaoConfig.getIdentityScope().clear();
    }

    public FavDao getFavDao() {
        return favDao;
    }

    public CateDao getCateDao() {
        return cateDao;
    }

    public ArticleListDao getArticleListDao() {
        return articleListDao;
    }

}
